# Generated by Django 4.1.1 on 2022-09-26 09:24

from django.db import migrations, models
import django.db.models.deletion
import datetime
from django.utils import timezone

def load_initial_data(apps, schema_editor):

    question_model = apps.get_model('polls', 'Question')
    q1 = question_model.objects.create (
        question_text = "你了解抖音云吗？", pub_date = timezone.now()
    )
    q2 = question_model.objects.create (
        question_text = "最关注抖音云的什么能力？", pub_date = timezone.now()
    )

    choice_model = apps.get_model('polls', 'Choice')
    choice_model.objects.create (
        question = q1, choice_text = "了解，抖音云是服务于抖音开放生态的云托管服务"
    )
    choice_model.objects.create (
        question = q1, choice_text = "不了解，我抓紧时间去学习了解，给我带来更多价值"
    )

    choice_model = apps.get_model('polls', 'Choice')
    choice_model.objects.create (
        question = q2, choice_text = "秒级动态扩缩容"
    )
    choice_model.objects.create (
        question = q2, choice_text = "免鉴权免解密"
    )
    choice_model.objects.create (
        question = q2, choice_text = "持续集成、灰度发布"
    )
    choice_model.objects.create (
        question = q2, choice_text = "云资源价格低"
    )

class Migration(migrations.Migration):


    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(load_initial_data),
    ]
